name: Deploy Site

on:
    push:
        branches:
            - main # Activa el job cuando se hace un push a la rama main

permissions: # sirve para dar permisos a los jobs
    contents: write # permite escribir en el repositorio

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4 # Clona el repositorio en el runner

            - name: Setup Node.js
              uses: actions/setup-node@v4 # Configura Node.js
              with:
                node-version: '20'
                cache: 'npm'
            
            - name: Install Dependencies # Instala las dependencias
              run: npm install

            - name: Build # Compila el proyecto
              run: npm run build
            
            - name: Deploy to Dev # Despliega el proyecto en la rama gh-pages
              uses: peaceiris/actions-gh-pages@v4
              with: 
                github_token: ${{ secrets.GITHUB_TOKEN }} # Token de acceso a GitHub
                publish_dir: ./dist # Directorio a publicar